name: Dynamic Baseline Scan

on:
  #push:
  workflow_dispatch: # to allow to run manually

permissions: # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  contents: read
  issues: write


jobs:

  DAST-Baseline-Scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Setup Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: cd marathon || :; mvn clean install -DskipTests

      - name: Deploy Marathon for Local Integration Tests
        run: cd marathon || :; cd integration && ./start-integration.sh

      # https://github.com/marketplace/actions/owasp-zap-baseline-scan
      # https://www.zaproxy.org/docs/docker/baseline-scan/
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed
        with:
          target: 'http://localhost:9090/marathon'
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'        